### ISSUE TITLE
can we destroy pthread_mutex objects in locked state?

### ISSUE THREAD

**Issue by thtfpcuser** [neosmart/pevents#1]
i have tried pevents project on embedded linux. 
before we call neosmart_wfmo_t_::Destroy(),
neosmart_wfmo_t_::Mutex is in locked state,
could this mutex object be destroyed successfully?

this embedded device has arm cpu, 
runs linux kernel 3.10.31, pthread library 2.19, 
i find in neosmart_wfmo_t_::Destroy(),
call to pthread_mutex_destroy failed, error number is EBUSY. 

is this an issue, which leads to resource leak?

**Comment by mqudsi** [comment]
Hello thtfpcuser,

Thanks for your email and your question.

This is a common question we get, though the problem is likely not with pevents. This is a problem with the original code, if you track it down on Windows you'll note a first-chance exception under the same circumstances.

You must release all instances of the event before calling DestroyEvent; it is an error not to do so. **You cannot delete an event that is still being waited on by another thread.**

The easiest way to retrofit old code to do this is to create another event, call it "all tasks done", make sure it's reset, and have the cleanup code wait on this event before calling DestroyEvent. Once all tasks have finished, set the event. e.g. 

````
void DoSomething()
{
	//Do something useful
	//Use someEvent for something useful
	WaitForEvent(someEvent);
	//Do something else
	SetEvent(someEvent);

	//After finishing:
	if (InterlockedDecrement(remainingTasks) == 0)
	{
		SetEvent(tasksDone)
	}
}

int remainingTasks = tasksCount;
neosmart_event_t someEvent = CreateEvent(false);
neosmart_event_t tasksDone = CreateEvent(true, false);

for (int i = 0; i < tasksCount; ++i)
{
	StartThread(DoSomething);
}

WaitForEvent(tasksDone);
DestroyEvent(someEvent);
DestroyEvent(tasksDone);
````

The old code was crashing when you attempt to call `DestroyEvent(someEvent)` because a random thread might be waiting on it. Here we added the event `tasksDone` and used `InterlockedDecrement` to set tasksDone when all tasks have finished. This way we only call `DestroyEvent` when no event is waiting on `someEvent` any more.
