### ISSUE TITLE
Lost Wake-Up Problem

### ISSUE THREAD

**Issue by thtfpcuser** [neosmart/pevents#2]
[Lost Wake-Up Problem Described On Oracle Website](https://docs.oracle.com/cd/E36784_01/html/E36868/sync-30.html)

A call to pthread_cond_signal() or pthread_cond_broadcast() when the thread does not hold the mutex lock associated with the condition can lead to **lost wake-up** bugs.

``` C++
int SetEvent(neosmart_event_t event)
{
    int result = pthread_mutex_lock(&event->Mutex);
    /* .... */
    result = pthread_mutex_unlock(&event->Mutex);

    result = pthread_cond_signal(&event->CVariable);  // the thread does not hold the mutex lock.
    /* .... */
    return 0;
}

```

**Comment by mqudsi** [comment]
I think we're OK; I'll explain what how I see it and you can tell me if I'm missing something.

The key part of the documentation you linked to is this:

> This can occur only if the condition being tested is modified without holding the mutex lock associated with the condition. As long as the condition being tested is modified only while holding the associated mutex, pthread_cond_signal() and pthread_cond_broadcast() can be called regardless of whether they are holding the associated mutex.

What will determine if there's a race condition or not is whether the test that is performed before a call to `pthread_cond_(timed)_wait` can be changed without the mutex that the thread calling `pthread_cond_(timed)wait` has exclusively obtained.

There are two calls to `pthread_cond_(timed)wait` (two sets of one timed and one untimed call, each). 

The first is for the event mutex and condition variable, the calling thread has an exclusive lock over `event->Mutex` and tests the value of `event->State` to determine whether or not we should wait on a condition variable because the event isn't ready yet. `event->State` is never touched without first obtaining the mutex `event->Mutex` (except in the call to `CreateEvent`, but no one has a handle to that event yet, so it doesn't matter).

The second is for the wfmo state synchronization object, and the test that decides whether we wait on the condition variable is 
`done = (waitAll && wfmo->Status.EventsLeft == 0) || (!waitAll && wfmo->Status.FiredEvent != -1);`
where `waitAll` is a local variable that never changes, so we just have to look at `Status.EventsLeft` and `Status.FiredEvent` and ensure they could never flip their value if we've obtained the mutex `wfmo->Mutex` before we give it up when waiting on the condition variable `wfmo->CVariable`.

I've looked at all the modifications to these two wfmo fields, and I can't see any that are performed without first obtaining `wfmo->Mutex` or `waiter->Mutex`. Each `FiredEvent`/`EventsLeft` instance describes the state of exactly one `wfmo` wait, i.e. these objects aren't shared between multiple wfmo instances.

Since the variables that determine whether or not we enter the condition variable wait are only ever modified after obtaining the mutex that the calling thread owns and gives up only when waiting on the condition variable, there's no way that the result of the test could change in between the time the test is evaluated and the condition variable is waited on.

**Comment by thtfpcuser** [comment]
The second case, wfmo state synchronization object, we have a problem with timed waiting.

In multiple threads environment, when `SetEvent` function step (S2) finishes, 
we switch to `WaitForMultipleEvents` function, 
we execute step (W3), return due to timeout, 
and continue to execute step (W4) (W5).
After we destroy condition variable, 
we switch to `SetEvent` function, the function executes step (S3), 
this is a `pthread_cond_signal` call on a destroyed condition variable, 
behavior is undefined, thread may stuck in function `pthread_cond_signal`.

(W1)In function `WaitForMultipleEvents`, when we enter the function, we allocate a wfmo object, it contains mutex lock and condition variable.
`UPF_OS_wfmo_t wfmo = new UPF_OS_wfmo_t_;`


(W2)Then we locked the mutex.
`tempResult = pthread_mutex_lock(&wfmo->Mutex);`


(W3)after lock the mutex, we call timed wait. 
`result = pthread_cond_timedwait(&wfmo->CVariable, &wfmo->Mutex, &ts);`
When waiting begins, mutex is unlocked by `pthread_cond_timedwait`。
when timeout arrives, waiting ends, mutex is locked by `pthread_cond_timedwait` again.

(W4)Then `WaitForMultipleEvents` function calls unlock.
`tempResult = pthread_mutex_unlock(&wfmo->Mutex);`


(W5)If there is no other reference to wfmo object, it will be deleted.
`wfmo->Destroy();`
`delete wfmo;`

(S1)In the waiting step (W3) of `WaitForMultipleEvents` function, `SetEvent` is called. Waiter is a wfmo object, we lock the mutex in it.

`result = pthread_mutex_lock(&i->Waiter->Mutex);`

(S2)After some operations , we unlock mutex.
`result = pthread_mutex_unlock(&i->Waiter->Mutex);`


(S3)After unlock, we call `pthread_cond_signal`.
`result = pthread_cond_signal(&i->Waiter->CVariable);`


There is a modified version of [pevents](https://github.com/Microsoft/WinObjC/blob/develop/Frameworks/Starboard/pevents.cpp) in [WinObjC](https://github.com/Microsoft/WinObjC/) project.
After modification, calls to `pthread_cond_signal` and `pthread_cond_broadcast` are all between `pthread_mutex_lock` and `pthread_mutex_unlock`.
However, revision history is incomplete, there is no explanation for reason of modification.

**Comment by mqudsi** [comment]
OK, I'm not sure if I'm following you one hundred percent. In your last comment, are you reporting one issue or two?

We use refcounting to prevent the pthreads condition variable from being destroyed until no more references to the WFMO object are in memory. Each time a wait is registered with a blocked event, the refcount is incremented, and when a wait succeeds the refcount is decremented. In fact, the issue we have is that WFMO objects and their associated synchronization primitives can stay in memory for a _very_ long time if you repeatedly call `WaitForMultipleEvents` and include an event that is never (or is very rarely) set, because they would accumulate in that event's WFMO queue.

That's the reason for pevents.cpp:280

			//Before adding this wait to the list of registered waits, let's clean up old, expired waits while we have the event lock anyway
			events[i]->RegisteredWaits.erase(std::remove_if (events[i]->RegisteredWaits.begin(), events[i]->RegisteredWaits.end(), RemoveExpiredWaitHelper), events[i]->RegisteredWaits.end());

This prevents these locks from accumulating indefinitely in memory.

**Comment by mqudsi** [comment]
This is a diff of the current version of pevents.cpp from WinObjc vs from this repository. They're using an older version of the code as their base, so there are some minor changes that can be disregarded (struct member order, `PulseEvents`, etc.): [pevents comparison.pdf](https://github.com/neosmart/pevents/files/900275/pevents.comparison.pdf)

I see they added support for waiting on sockets to WaitForMultipleEvents, and that's implemented exclusively in an if branch before our code for waiting on the wfmo events.  The order of pthread_*unlock and `pthread_cond_signal` and `pthread_mutex_unlock` has indeed been reversed, but like you said, without a proper repo history that could be anything. I think in _their_ case it is actually required since if they are waiting on sockets, that _could_ change without the mutex being obtained, no longer qualifying for the exception in the Oracle document on condition variable signalling while not holding the mutex.

The only other change is that they made `DestroyEvent` safe to call while other threads are WFMO waiting, but that's a pointless change because 
a) the waiting threads will remain blocked forever if they are waiting on an event that is deleted before they return (so bad code design in code using pevents or even regular WIN32 events).
b) they still don't solve anything since other code may be WFSO blocked on the same mutex/cv, and when/if they wake (or even spurious wake!) they will be performing operations on a now-deleted mutex/cv, which is undefined behavior in all cases.

We've dealt with many requests to make `DeleteEvent()` safe to call (except they all come in the form of "there's a bug in your code, something is crashing" but it turns out they are calling `DeleteEvent()` while other threads are waiting on that object. That's bad code and *must* be refactored. I've said it many times and I'll say it again, whether you are using WIN32 events, pthread CVs, or pevents, you need to add an additional signal (event) that is unset until *all* threads that would wait on a particular pevent/mutex/critical section/event/whatever have completed, and block on this event before calling DestroyEvent.

**Comment by mqudsi** [comment]
OK, I've reviewed the changes between the WinObjC port of the pevents code and our own.

I think the reason they switched the `pthread_mutex_unlock` and `pthread_cond_signal` is because they have added the ability to wait on sockets (or, rather, file descriptors) to `WaitForMultipleEvents`, which means that they're no longer qualifying for the exception that we are relying on (the condition that determines whether or not the code will go into the condition variable wait. Or out of an abundance of caution. It could be either.

However, their code did point out something important: the behavior of `pthread_mutex_destroy` is undefined if the mutex is still owned. To prevent against calling code starting a wait on the same mutetx before we delete the event, we kept holding it until the destroy; but that is not correct behavior and we can't protect users from themselves, anyway. The library needs to be modified to call `pthread_mutex_destroy` before calling the `DestroyEvent()` code.

The second thing is that we call `RemoveExpiredWaitHelper()` in `DestroyEvent()` to clean up any outstanding references to the event being deleted. However, `RemoveExpiredWaitHelper()` only does a best-effort removal of waits, and so it doesn't guarantee that a wait currently processing a WFMO call will end up _safely_ no longer waiting on this event. In the WinObjC version of pevents, the `pthread_mutex_trylock` we use is replaced with an unrolled `pthread_mutex_lock` call. 

However, we only use `RemoveExpiredWaitHelper()` here as a courtesy, I reiterate as I have many times before when people complain of random crashes that in _no_ synchronization API (be it WIN32 events, pthreads, or pevents) is it safe to delete an event/object that is currently being waited on. That is a recipe for disaster and code must be changed to signal some sort of "done" event that the cleanup thread will block on before calling `DestroyEvent()`. It is bad (as in, completely wrong) design to do anything else. We _could_ change the code in `DestroyEvent()` to be blocking instead of best effort like WinObjC did, but there's really no point since a WFSO call can't be pre-empted and so there's still going to be attempts to access a deleted mutex/condition variable in that case.

**Comment by thtfpcuser** [comment]
For the second case, when we use wfmo object with timed wait, we encounter a trap.
In the end of function `WaitForMultipleEvents`, we have call to `Destroy` and `delete`.
`wfmo->Destroy();`
`delete wfmo`

In Function `SetEvent`, we have call to `pthread_cond_signal`.
`result = pthread_cond_signal(&i->Waiter->CVariable);`

Call to `pthread_cond_signal` can happen after `Destroy` and `delete`.
It can lead to crash or deadlock.

**Comment by thtfpcuser** [comment]
In function `WaitForMultipleEvents`, we have a `while (!done)` loop, 
after we return from `pthread_cond_timedwait` with `ETIMEDOUT` return value, we break the loop.
At this time, I think we have to check "done condition" again.
`done = (waitAll && wfmo->Status.EventsLeft == 0) || (!waitAll && wfmo->Status.FiredEvent != -1);`

Because the "done condition" can be changed by `SetEvent` during timed wait process, 
call to `pthread_cond_signal` can happen later, after timed wait process returns due to time out.
`result = pthread_cond_signal(&i->Waiter->CVariable);`

When "done condition" is true, return value of `WaitForMultipleEvents` should be 0.

**Comment by mqudsi** [comment]
@thtfpcuser it took me a long time to understand the point you were making here.

Yes, if we received `ETIMEDOUT` and _then_ `pthread_cond_signal()` was called, `WaitForMultipleEvents` will not return 0. But this is by design. and is not considered a bug. How does the calling code handle the situation where `pthread_cond_signal()` is called _after_ a hypothetical additional done check is added? It's not possible for us to ever _guarantee_ that event remains blocked at the time control passes back to the calling function.

Additionally, consider the semantics. We were asked to wait for n nanoseconds for this event. Those n nanoseconds elapsed and the event was not available (hence the `ETIMEDOUT`). We could add a `sleep(10)` after that and _still_ wouldn't be responsible to check what the event's status was after that delay - the time we were asked to wait expired and that's all we guarantee we will report back.

I think the problem here might stem from a poor multithreading model that is inherently vulnerable to race conditions in the calling code. While mitigations in pevents might work around that, they would just be further obscuring the underlying problems. The calling code shouldn't be vulnerable to timing issues like this; my guess is that there needs to be an additional layer of synchronization (one more event) in the consumer code.

If I misunderstood your point, please re-open.
